export { supabase, TIMEOUTS, SUPABASE_STORAGE_KEY } from './supabase';
export type { User, Community, Post, LiveInterest, Comment, UserRole } from './supabase';
export type { Event, EventParticipant, EventType, RitualType, EventStatus, LocationType, ParticipantStatus } from './supabase';
// useProfile e useCommunities são LEGADOS — usar useProfileContext e useCommunitiesContext
// export { useProfile } from './useProfile';
// export { useCommunities } from './useCommunities';
export { usePosts } from './usePosts';
export type { PostWithAuthor } from './usePosts';
export { useComments } from './useComments';
export type { CommentWithAuthor } from './useComments';
export { useImageUpload } from './useImageUpload';
export { useSeats } from './useSeats';
export type { CommunityWithMeta } from './CommunitiesContext';
export { COMMUNITIES_CONFIG, COMMUNITY_BY_NAME } from './communitiesConfig';
export type { CommunityConfig } from './communitiesConfig';
export { hasAppAccess, hasModAccess, hasLeadershipAccess, isSuperAdmin, needsLeadershipOnboarding, getDefaultPage, normalizeRole } from './roleEngine';
export { ProfileProvider, useProfileContext } from './ProfileContext';
export { CommunitiesProvider, useCommunitiesContext } from './CommunitiesContext';
export { usePlatformCopy, useHomeSections, useLegalPage, useLegalPages, useAnnouncements } from './useCMS';
export type { PlatformCopy, HomeSection, LegalPage, LegalPageKey, Announcement } from './useCMS';
export { useEvents, useEventDetail, EVENT_TYPE_LABELS, RITUAL_TYPE_LABELS, RITUAL_TYPE_DESCRIPTIONS, EVENT_STATUS_LABELS, LOCATION_TYPE_LABELS } from './useEvents';
export type { EventWithMeta, CreateEventInput } from './useEvents';